### ISSUE TITLE
error: exclude is not defined

### ISSUE THREAD

**Issue by RedaBenh** [enreeco/sf-git#1]
Hi,

I just deploy the app to heroku, I get this error when running the job `node bin/run-sfgit.js`

```
Running node bin/run-sfgit.js on sf-git... up, run.4106
SF LOGIN
SF DESCRIBE METADATA
SF LIST DESCRIBE METADATA ALL
SF LIST DESCRIBE METADATA: [{"type":"InstalledPackage"},{"type":"CustomLabels"},{"type":"StaticResource"}]
SF LIST DESCRIBE METADATA: [{"type":"Scontrol"},{"type":"AuraDefinitionBundle"},{"type":"ApexComponent"}]
SF LIST DESCRIBE METADATA: [{"type":"ApexPage"},{"type":"Queue"},{"type":"ExternalDataSource"}]
SF LIST DESCRIBE METADATA: [{"type":"NamedCredential"},{"type":"Role"},{"type":"Group"}]
SF LIST DESCRIBE METADATA: [{"type":"CustomObject"},{"type":"ReportType"},{"type":"Report"}]
SF LIST DESCRIBE METADATA: [{"type":"Dashboard"},{"type":"AnalyticSnapshot"},{"type":"CustomFeedFilter"}]
SF LIST DESCRIBE METADATA: [{"type":"Layout"},{"type":"Document"},{"type":"CustomPageWebLink"}]
SF LIST DESCRIBE METADATA: [{"type":"QuickAction"},{"type":"FlexiPage"},{"type":"CustomTab"}]
SF LIST DESCRIBE METADATA: [{"type":"CustomApplicationComponent"},{"type":"CustomApplication"},{"type":"Portal"}]
SF LIST DESCRIBE METADATA: [{"type":"Letterhead"},{"type":"EmailTemplate"},{"type":"Flow"}]
SF LIST DESCRIBE METADATA: [{"type":"FlowDefinition"},{"type":"Workflow"},{"type":"AssignmentRules"}]
SF LIST DESCRIBE METADATA: [{"type":"AutoResponseRules"},{"type":"EscalationRules"},{"type":"PostTemplate"}]
SF LIST DESCRIBE METADATA: [{"type":"ApprovalProcess"},{"type":"HomePageComponent"},{"type":"HomePageLayout"}]
SF LIST DESCRIBE METADATA: [{"type":"CustomObjectTranslation"},{"type":"Translations"},{"type":"ApexClass"}]
SF LIST DESCRIBE METADATA: [{"type":"ApexTrigger"},{"type":"Profile"},{"type":"PermissionSet"}]
SF LIST DESCRIBE METADATA: [{"type":"CustomMetadata"},{"type":"DataCategoryGroup"},{"type":"RemoteSiteSetting"}]
SF LIST DESCRIBE METADATA: [{"type":"MatchingRules"},{"type":"AuthProvider"},{"type":"CustomSite"}]
SF LIST DESCRIBE METADATA: [{"type":"ChannelLayout"},{"type":"SharingRules"},{"type":"Community"}]
SF LIST DESCRIBE METADATA: [{"type":"CallCenter"},{"type":"MilestoneType"},{"type":"EntitlementProcess"}]
SF LIST DESCRIBE METADATA: [{"type":"EntitlementTemplate"},{"type":"ConnectedApp"},{"type":"AppMenu"}]
SF LIST DESCRIBE METADATA: [{"type":"CustomPermission"},{"type":"SiteDotCom"},{"type":"CorsWhitelistOrigin"}]
SF LIST DESCRIBE METADATA: [{"type":"ActionLinkGroupTemplate"},{"type":"SynonymDictionary"},{"type":"PathAssistant"}]
SF LIST DESCRIBE METADATA: [{"type":"PlatformCachePartition"},{"type":"Settings"}]
SF RETRIEVE ZIP
GIT CLONE
/app/sfgit.js:33
        if(!excludeFolder || file != exclude){
                                     ^

ReferenceError: exclude is not defined
    at /app/sfgit.js:33:38
    at Array.forEach (native)
    at deleteFolderRecursive (/app/sfgit.js:30:26)
    at /app/sfgit.js:178:21
    at /app/node_modules/gift/lib/index.js:63:14
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

Any suggestion to resolve this issue ?

Thanks for your help.

Reda

**Comment by enreeco** [comment]
There was a mispelling in a variable. I've commited the fix.
Thanks for the feedback.

**Comment by RedaBenh** [comment]
great if fixed
